### ISSUE TITLE
rpc.statd failure when mounting NFS shares (IPX)

### ISSUE THREAD

**Issue by atleberg** [coreos/coreos-overlay#684] opened 2014-06-13 11:05 UTC
I'm trying to mount NFS shares, using cloud-config, which fails since rpc.statd can't open /etc/netconfig. I'm using the lates PXE image from the alpha channel and cloud-config for the configuration. With this setup the /etc/netconfig doesn't exist so I'm not surprised.

Touching the file manually or even filling it with a known to work gentoo configuration does not seem to help.

Original error message below follows.

core@stripe001 ~ $ journalctl -u fileserver.mount
-- Logs begin at Fri 2014-06-13 09:04:04 UTC, end at Fri 2014-06-13 09:10:36 UTC. --
Jun 13 09:04:14 stripe001 systemd[1]: Mounting /fileserver...
Jun 13 09:04:14 stripe001 rpc.statd[3044]: Version 1.2.9 starting
Jun 13 09:04:14 stripe001 rpc.statd[3044]: Flags: TI-RPC
Jun 13 09:04:14 stripe001 rpc.statd[3044]: rpc: failed to open /etc/netconfig
Jun 13 09:04:24 stripe001 mount[3022]: mount.nfs: rpc.statd is not running but is required for remote locking.
Jun 13 09:04:24 stripe001 mount[3022]: mount.nfs: Either use '-o nolock' to keep locks local, or start statd.
Jun 13 09:04:24 stripe001 mount[3022]: mount.nfs: an incorrect mount option was specified
Jun 13 09:04:24 stripe001 systemd[1]: fileserver.mount mount process exited, code=exited status=32
Jun 13 09:04:24 stripe001 systemd[1]: Failed to mount /fileserver.
Jun 13 09:04:24 stripe001 systemd[1]: Unit fileserver.mount entered failed state.

**Comment by ZimboBoyd** [comment] 2015-02-23 19:29
I can confirm that on a PXE booted coreos 598.0.0 there is no /etc/netconfig

If i create with
  - path: /etc/netconfig
    permissions: 0644
    content: |
      udp        tpi_clts      v     inet     udp     -       -
      tcp        tpi_cots_ord  v     inet     tcp     -       -
      udp6       tpi_clts      v     inet6    udp     -       -
      tcp6       tpi_cots_ord  v     inet6    tcp     -       -
      rawip      tpi_raw       -     inet      -      -       -
      local      tpi_cots_ord  -     loopback  -      -       -
      unix       tpi_cots_ord  -     loopback  -      -       -

the file

NFS3 mounts start to work

**Comment by AntonioMeireles** [comment] 2015-03-13 09:48
afaict, fwiw, this is fixed in recent CoreOS alphas.

**Comment by mischief** [comment] 2015-03-13 20:28
/etc/netconfig should be present in pxe images now. also, /etc/conf.d is gone and the systemd units from the nfs ebuild no longer refer to them.

**Comment by marineam** [comment] 2015-03-13 21:39
@mischief can this be closed then?

**Comment by mischief** [comment] 2015-03-16 18:09
yes, should be solved since coreos/coreos-overlay#1130

**Closed by mischief** 2015-03-16 18:09 UTC
